"""fix_timezone_to_false

Revision ID: 244701d3834c
Revises: 481836fae051
Create Date: 2026-05-07 08:37:02.388805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '244701d3834c'
down_revision: Union[str, Sequence[str], None] = '481836fae051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('avaliabilites', 'start_time',
               existing_type=postgresql.TIME(timezone=True),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('avaliabilites', 'end_time',
               existing_type=postgresql.TIME(timezone=True),
               type_=sa.Time(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('avaliabilites', 'end_time',
               existing_type=sa.Time(),
               type_=postgresql.TIME(timezone=True),
               existing_nullable=False)
    op.alter_column('avaliabilites', 'start_time',
               existing_type=sa.Time(),
               type_=postgresql.TIME(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
