"""fix_tipo_crp

Revision ID: 8b8d9956e19b
Revises: 8a4512f62a98
Create Date: 2026-05-02 21:18:15.829608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8d9956e19b'
down_revision: Union[str, Sequence[str], None] = '8a4512f62a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('psychologists', 'crp',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'psychologists', ['crp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'psychologists', type_='unique')
    op.alter_column('psychologists', 'crp',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
